In [1]:
using CSV
using Statistics
using DataFrames
using StatsBase  # For standardization

In [2]:
file_path = "student-mat.csv"
df = CSV.read(file_path)
m = convert(Matrix, df)

395×33 Array{Any,2}:
 "GP"  "F"  18  "U"  "GT3"  "A"  4  4  …  4  3  4  1  1  3   6   5   6   6
 "GP"  "F"  17  "U"  "GT3"  "T"  1  1     5  3  3  1  1  3   4   5   5   6
 "GP"  "F"  15  "U"  "LE3"  "T"  1  1     4  3  2  2  3  3  10   7   8  10
 "GP"  "F"  15  "U"  "GT3"  "T"  4  2     3  2  2  1  1  5   2  15  14  15
 "GP"  "F"  16  "U"  "GT3"  "T"  3  3     4  3  2  1  2  5   4   6  10  10
 "GP"  "M"  16  "U"  "LE3"  "T"  4  3  …  5  4  2  1  2  5  10  15  15  15
 "GP"  "M"  16  "U"  "LE3"  "T"  2  2     4  4  4  1  1  3   0  12  12  11
 "GP"  "F"  17  "U"  "GT3"  "A"  4  4     4  1  4  1  1  1   6   6   5   6
 "GP"  "M"  15  "U"  "LE3"  "A"  3  2     4  2  2  1  1  1   0  16  18  19
 "GP"  "M"  15  "U"  "GT3"  "T"  3  4     5  5  1  1  1  5   0  14  15  15
 "GP"  "F"  15  "U"  "GT3"  "T"  4  4  …  3  3  3  1  2  2   0  10   8   9
 "GP"  "F"  15  "U"  "GT3"  "T"  2  1     5  2  2  1  1  4   4  10  12  12
 "GP"  "M"  15  "U"  "LE3"  "T"  4  4     4  3  3  1  3  5   2  14  14  14
 ⋮  

In [3]:
school_vector = Array{String,1}(undef, size(m)[1])
sex_vector = Array{String,1}(undef, size(m)[1])
address_vector = Array{String,1}(undef, size(m)[1])
famsize_vector = Array{String,1}(undef, size(m)[1])
pstatus_vector = Array{String,1}(undef, size(m)[1])
mjob_vector = Array{String,1}(undef, size(m)[1])
fjob_vector = Array{String,1}(undef, size(m)[1])
reason_vector = Array{String,1}(undef, size(m)[1])
guardian_vector = Array{String,1}(undef, size(m)[1])
schoolsup_vector = Array{String,1}(undef, size(m)[1])
famsup_vector = Array{String,1}(undef, size(m)[1])
paid_vector = Array{String,1}(undef, size(m)[1])
activities_vector = Array{String,1}(undef, size(m)[1])
nursery_vector = Array{String,1}(undef, size(m)[1])
higher_vector = Array{String,1}(undef, size(m)[1])
internet_vector = Array{String,1}(undef, size(m)[1])
romantic_vector = Array{String,1}(undef, size(m)[1])

395-element Array{String,1}:
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
   ⋮   
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef
 #undef

In [4]:
# Please make refactor me
for i in 1:size(m)[1]
    for j in 1:size(m)[2]
        if j == 1
            school_vector[i] = m[i,j]

        elseif j == 2
            sex_vector[i] = m[i,j]
        elseif j == 4
            address_vector[i] = m[i,j]
        elseif j == 5
            famsize_vector[i] = m[i,j]
        elseif j == 6
            pstatus_vector[i] = m[i,j]
        elseif j == 9
            mjob_vector[i] = m[i,j]
        elseif j == 10
            fjob_vector[i] = m[i,j]
        elseif j == 11
            reason_vector[i] = m[i,j]
        elseif j == 12
            guardian_vector[i] = m[i,j]
        elseif j == 16
            schoolsup_vector[i] = m[i,j]
        elseif j == 17
            famsup_vector[i] = m[i,j]
        elseif j == 18
            paid_vector[i] = m[i,j]
        elseif j == 19
            activities_vector[i] = m[i,j]
        elseif j == 20
            nursery_vector[i] = m[i,j]
        elseif j == 21
            higher_vector[i] = m[i,j]
        elseif j == 22
            internet_vector[i] = m[i,j]
        elseif j == 23
            romantic_vector[i] = m[i,j]
        end
        # println()
    end
    # mv = Array{String}(undef, length(m))
    # println(m[i,1])
end

In [5]:
function map_to_int(arr)
    # Dynamically map the strings to numbers
    unique_list = String[]
    for v in arr
        if v in unique_list
            continue
        else
            push!(unique_list, v)
        end
    end
    # println(unique_list)
    cleaned_list = Array{Int64, 1}(undef, length(arr))
    count = 1
    for i in unique_list
        for j in 1:length(arr)
            if arr[j] == i
                cleaned_list[j] = count
            end
        end
        count += 1
    end
    return cleaned_list

end

cleaned_school = map_to_int(school_vector)
cleaned_sex = map_to_int(sex_vector)
cleaned_address = map_to_int(address_vector)
cleaned_famsize = map_to_int(famsize_vector)

cleaned_pstatus = map_to_int(pstatus_vector)
cleaned_mjob = map_to_int(mjob_vector)
cleaned_fjob = map_to_int(fjob_vector)
cleaned_reason = map_to_int(reason_vector)

cleaned_guardian = map_to_int(guardian_vector)
cleaned_schoolsup = map_to_int(schoolsup_vector)
cleaned_famsup = map_to_int(famsup_vector)
cleaned_paid = map_to_int(paid_vector)

cleaned_activities = map_to_int(activities_vector)
cleaned_nursery = map_to_int(nursery_vector)
cleaned_higher = map_to_int(higher_vector)
cleaned_internet = map_to_int(internet_vector)

cleaned_romantic = map_to_int(romantic_vector)

395-element Array{Int64,1}:
 1
 1
 1
 2
 1
 1
 1
 1
 1
 1
 1
 1
 1
 ⋮
 1
 1
 1
 2
 1
 1
 1
 1
 1
 1
 1
 1

In [6]:
# 2. Extract outcome and features
# 2.1 Create outcome vector
y = Array{Int64, 1}(undef, size(m)[1])
for i in 1:size(m)[1] # rows
    temp_total = 0
    for j in 31:size(m)[2] # From G1 to G3
        temp_total += m[i,j]
    end
    # Find average of grade and set value in outcome 1 if average is > 10 else 0
    if (temp_total/3) >= 10
        global y[i] = 1
    else
        global y[i] = 0
    end
end

In [23]:
println(y)

[0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 

In [7]:
# 2.2 Update the changes to the matrix to the numerical equivalents
# TODO: Create vectors for the features then concatenate them. Below not functioning as expected

for i in 1:size(m)[1]
    for j in 1:size(m)[2]
        if j == 1
            m[i,j] = cleaned_school[i]
        elseif j == 2
            m[i,j] = cleaned_sex[i]
        elseif j == 4
            m[i,j] = cleaned_address[i]
        elseif j == 5
            m[i,j] = cleaned_famsize[i]
        elseif j == 6
            m[i,j] = cleaned_pstatus[i]
        elseif j == 9
            m[i,j] = cleaned_mjob[i]
        elseif j == 10
            m[i,j] = cleaned_fjob[i]
        elseif j == 11
            m[i,j] = cleaned_reason[i]
        elseif j == 12
            m[i,j] = cleaned_guardian[i]
        elseif j == 16
            m[i,j] = cleaned_schoolsup[i]
        elseif j == 17
            m[i,j] = cleaned_famsup[i]
        elseif j == 18
            m[i,j] = cleaned_paid[i]
        elseif j == 19
            m[i,j] = cleaned_activities[i]
        elseif j == 20
            m[i,j] = cleaned_nursery[i]
        elseif j == 21
            m[i,j] = cleaned_higher[i]
        elseif j == 22
            m[i,j] = cleaned_internet[i]
        elseif j == 23
            m[i,j] = cleaned_romantic[i]
        end
    end
end

# Remove G1, G2 and G3 from matrix by writing all except unwanted. Note: deleteat! won't work with 2 dims
x = Matrix{Float64}(undef, size(m)[1], size(m)[2]-3)

for i in 1:size(m)[1]
    for j in 1:size(m)[2]-3
        # Merge the outcome value as the last index
        if j == size(m)[2]-3
            x[i,j] = y[i]
            continue
        end
        x[i,j] = m[i,j]
    end
end

In [8]:
# Standardize x
m_fit = fit(ZScoreTransform, x, dims=2)
x = StatsBase.transform(m_fit, x)

395×30 Array{Float64,2}:
 -0.341606   -0.341606   4.93775  …  -0.341606   0.279495  -0.652156
 -0.35633    -0.35633    4.98862     -0.35633    0.311789  -0.690389
 -0.42453    -0.42453    4.97858      0.347343   0.347343  -0.810467
 -0.497143   -0.497143   4.8567      -0.497143   1.03253   -0.497143
 -0.461313   -0.461313   4.86153     -0.106457   0.958111  -0.816169
 -0.564228   -0.211586   4.72541  …  -0.211586   0.846342  -0.564228
 -0.453874   -0.0955524  4.92095     -0.453874   0.262769  -0.453874
 -0.361375   -0.361375   4.89499     -0.361375  -0.361375  -0.689897
 -0.436536   -0.0513572  4.95597     -0.436536  -0.436536  -0.436536
 -0.528424   -0.159756   4.63293     -0.528424   0.946248  -0.528424
 -0.518776   -0.518776   4.66899  …  -0.148222  -0.148222  -0.889331
 -0.501897   -0.501897   4.76802     -0.501897   0.627371  -0.501897
 -0.556453   -0.177053   4.75515      0.202347   0.961147  -0.556453
  ⋮                               ⋱                                 
 -0.10024

In [388]:
# Split into testing and training
TEST_PERCENT = 0.8
# Calculate number of rows to use as test sample
testing_row_length = trunc(Int64, size(x)[1] * TEST_PERCENT)
training_x = x[1:testing_row_length-1, :]
testing_x = x[testing_row_length: size(x)[1], :]

training_y = y[1:testing_row_length-1, :]
testing_y = y[testing_row_length: size(y)[1], :]


80×1 Array{Int64,2}:
 1
 0
 0
 1
 1
 1
 0
 1
 1
 1
 1
 1
 1
 ⋮
 0
 0
 0
 0
 0
 0
 0
 0
 1
 0
 1
 0

In [389]:
# Concatenate a vector of 1 to feature matrix (training_x) to represent bias
training_x = hcat(training_x, ones(Int64, size(training_x)[1]))
testing_x = hcat(testing_x, ones(Int64, size(testing_x)[1]))

80×31 Array{Float64,2}:
 -0.427373   -0.427373  5.06742  -0.122107  …   0.18316   -0.427373  1.0
 -0.390441   -0.390441  4.99131  -0.390441     -0.390441  -0.707014  1.0
 -0.461053   -0.461053  4.88297  -0.461053      0.796365  -0.775408  1.0
 -0.558056   -0.558056  4.79928  -0.223222      0.781278  -0.558056  1.0
 -0.519343   -0.519343  4.77796  -0.519343      0.72708   -0.519343  1.0
 -0.462957   -0.462957  4.82798  -0.462957  …   0.859777  -0.462957  1.0
 -0.349871   -0.349871  5.06748  -0.349871      0.327299  -0.688456  1.0
 -0.472159   -0.472159  5.05556  -0.126677      0.218805  -0.472159  1.0
 -0.492232   -0.492232  4.87757  -0.492232      0.850219  -0.492232  1.0
 -0.437288   -0.437288  4.94472  -0.437288     -0.100913  -0.437288  1.0
 -0.458534   -0.138627  4.9799   -0.458534  …   0.181281  -0.458534  1.0
 -0.560999   -0.231     4.71899  -0.560999      0.758999  -0.560999  1.0
 -0.554784   -0.228441  4.66671  -0.228441      0.424247  -0.554784  1.0
  ⋮                        

In [407]:
# hypothesis becomes h(X) = X × Θ (a matrix multiplication).
# hθ(x) = g((θT x))
function hypothesis(v_theta, X)
    z = transpose(v_theta) * X
    return 1/(1+exp(-z))
end
# t = zeros(size(training_x)[2])
# hypothesis(t,training_x[1, :])

hypothesis (generic function with 1 method)

In [304]:
function sum_and_square_theta(arr)
    # Exclude first element of theta
#     return sum(arr[2:size(arr)[1]]) ^ 2
    a = sum(arr) - arr[1]
    return a^2

end

sum_and_square_theta (generic function with 2 methods)

In [423]:
function cost_function(X, Y, λ, theta)
    m = size(X)[1]
#     nfeatures = size(X)[1] - 1
#     theta = zeros(size(X)[2])
    cost = 0
    gradient = 0
    for i in 1:m
        x = X[i,:]
        y = Y[i]
        # cross entropy
        cost += (1/m)*(-y*log(hypothesis(theta, x)) - ((1-y) * log(1-hypothesis(theta, x))))
        cost += (λ/2m) * sum_and_square_theta(theta)
        gradient = ((1/m)*x) * (hypothesis(theta, x) - y) + (λ/m) * theta
#         println("Hypothesis: ",hypothesis(theta, x), ", Actual: ",y)
        # old
#         first_part = y * log(hypothesis(theta,x)) - (1-y) * log(1-hypothesis(theta, x))
#         second_part = (λ/2m) * sum_and_square_theta(theta)
#         cost += (1/m)*(first_part + second_part)
        # Update parameters for next iteration
        
#         grad = ((1/m)*x) * (hypothesis(theta, x) - y) + (λ/m) * theta
#         theta = theta - α * grad
    end
    
    return cost, gradient

    #
end


cost_function (generic function with 2 methods)

In [424]:
function gradient_descent(X, Y, theta, α, num_iterations, λ) # α -> learning rate
    tcost = 0
    m = size(X)[1]
    for i in 1:num_iterations
        cost, grad = cost_function(X, Y, λ, theta)
        theta = theta - (α*grad)
        tcost += cost
    end
    return theta, (tcost/num_iterations)
end

gradient_descent (generic function with 1 method)

In [425]:
predicate_theta, cost = gradient_descent(training_x, training_y, zeros(size(training_x)[2]), 0.2, 200, 0.2)
println("Average cost:", cost)
for i in 1: 10
    pred = hypothesis(predicate_theta, testing_x[i, :])
    println("Predicted: ",pred, ", Actual: ",testing_y[i])
end


Average cost:0.7031020483559332
Predicted: 0.7721622057749936, Actual: 1
Predicted: 0.7616625851512883, Actual: 0
Predicted: 0.7601616374718211, Actual: 0
Predicted: 0.7572470394565417, Actual: 1
Predicted: 0.750476061782137, Actual: 1
Predicted: 0.7596770921857244, Actual: 1
Predicted: 0.7677913319327275, Actual: 0
Predicted: 0.7633587890731406, Actual: 1
Predicted: 0.7606733346206329, Actual: 1
Predicted: 0.768426336648389, Actual: 1
